# Site settings
title: Logan Aaron's Blog
email: loganp82@gmail.com
description: A blog about my journey in the world of web design & development.
url: "" # the base hostname & protocol for your site
twitter_username: loganpeterson82
dribbble_username: loganaaron82
codepen_username: loganaaron
soundcloud_username: loganaaron
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

#Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Logan Peterson
      layout: "post"
      comments: true
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"
